# Generated by Django 3.2.13 on 2022-06-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20220617_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderReview',
        ),
    ]
