# Generated by Django 3.2.13 on 2022-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='light_need',
            field=models.CharField(blank=True, choices=[('++', 'Ginger Tan'), ('--', 'European')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='water_need',
            field=models.CharField(blank=True, choices=[('++', 'Big Drinker'), ('--', 'Teetotaler')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'small (< 15cm)'), ('medium', 'medium (15cm - 30cm)'), ('big', '> big (30cm)')], default='medium (15cm - 30cm)', max_length=400, null=True),
        ),
    ]
