# Generated by Django 3.2.13 on 2022-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220511_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('small (< 15cm)', 'small (< 15cm)'), ('medium (15cm - 30cm)', 'medium (15cm - 30cm)'), ('> big (30cm)', '> big (30cm)')], default='medium (15cm - 30cm)', max_length=400, null=True),
        ),
    ]
