# Generated by Django 3.2.13 on 2022-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('small (< 30cm)', 'small (< 30cm)'), ('medium (30cm - 60cm)', 'medium (30cm - 60cm)'), ('big (> 60cm)', 'big (> 60cm)')], default='medium (30cm - 60cm)', max_length=400, null=True),
        ),
    ]
